id: AB2AFE810
base_file: fDCBA.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:17:02.363762
  last_modified_at: 2022-06-17 14:17:02.363773
