id: AB2AFE810
base_file: fAADD.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:17:02.359320
  last_modified_at: 2022-06-17 14:17:02.359335
